[package]
name = "sbpf-asm-macros"
description = "Ergonomic macros for low-level sBPF ASM functionality"
authors = ["Dean Little <@deanmlittle>"]
version = "0.1.2"
edition = "2021"
license = "MIT"

[lib]
name = "sbpf_asm_macros"
crate-type = ["cdylib", "lib"]