[package]
name = "sbpf-asm-macros"
description = "Ergonomic macros for low-level sBPF ASM functionality"
authors = ["Dean Little <@deanmlittle>"]
version = "0.1.0"
edition = "2021"

[lib]
name = "sbpf_asm_macros"
crate-type = ["cdylib", "lib"]